name: 'KiCad PDF Generator'
description: 'Generates PDF files for all schematics and PCBs.'
inputs:
  output-path:
    description: 'The path to store the generated PDF files.'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Generate PDFs
      shell: bash
      env:
        LD_LIBRARY_PATH: /usr/lib/kicad-nightly/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH
      run: |
        find . -name "*.kicad_sch" -print0 | while IFS= read -r -d $'\0' file; do
          filename=$(basename "$file" .kicad_sch)
          dir=$(dirname "$file" | sed 's|^\./||')
          kicad-cli sch export pdf --output "${{ inputs.output-path }}/${dir//\//_}_${filename}_sch.pdf" "$file"
        done
        find . -name "*.kicad_pcb" -print0 | while IFS= read -r -d $'\0' file; do
          filename=$(basename "$file" .kicad_pcb)
          dir=$(dirname "$file" | sed 's|^\./||')
          kicad-cli pcb export pdf --output "${{ inputs.output-path }}/${dir//\//_}_${filename}_pcb.pdf" "$file" || true
        done
