name: 'KiCad PDF Generator'
description: 'Generates PDF files for all schematics and PCBs.'
inputs:
  output-path:
    description: 'The path to store the generated PDF files.'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Generate PDFs
      shell: bash
      env:
        LD_LIBRARY_PATH: /usr/lib/kicad-nightly/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH
      run: |
        set -x
        find . -name "*.kicad_sch" -print0 | while IFS= read -r -d $'\0' file; do
          echo "Processing schematic: $file"
          filename=$(basename "$file" .kicad_sch)
          dir=$(dirname "$file" | sed 's|^\./||')
          output_file="${{ inputs.output-path }}/${dir//\//_}_${filename}_sch.pdf"
          echo "Outputting to: $output_file"
          kicad-cli sch export pdf --output "$output_file" "$file"
        done
        find . -name "*.kicad_pcb" -print0 | while IFS= read -r -d $'\0' file; do
          echo "Processing PCB: $file"
          filename=$(basename "$file" .kicad_pcb)
          dir=$(dirname "$file" | sed 's|^\./||')
          output_file="${{ inputs.output-path }}/${dir//\//_}_${filename}_pcb.pdf"
          echo "Outputting to: $output_file"
          kicad-cli pcb export pdf --output "$output_file" "$file"
        done
    - name: Verify PDF generation
      shell: bash
      run: |
        if [ -z "$(ls -A ${{ inputs.output-path }}/*.pdf 2>/dev/null)" ]; then
          echo "Error: No PDF files found in ${{ inputs.output-path }}"
          exit 1
        fi
